apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo3
  template:
    metadata:
      labels:
        app: demo3
    spec:
      containers:
        - name: aloktest
          image: us-central1-docker.pkg.dev/my-playground-412717/playreg/aloktest:0.1
---
apiVersion: v1
kind: Service
metadata:
  name: demo3
spec:
  selector:
    app: demo3
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: ClusterIP