# This is a basic workflow to help you get started with Actions#
name: Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: "read"
      id-token: "write"

    env:
      # Replace $PROJECT_ID with your project ID
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      #IMAGE_NAME: gcr.io/playground-380006/alokreg/alokgit:0.0.1
      #PROJECT_ID: playground-380006
      IMAGE_NAME: alokgit:0.0.5
      REGION_NAME: us-central1
      REGISTRY_NAME: alokreg
      CLUSTER_NAME: playground-cluster-1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          # Replace with your Workload Identity Provider Location
          #workload_identity_provider: "$WORKLOAD_IDENTITY_PROVIDER_LOCATION"
          # Replace with your GitHub Service Account
          #service_account: "$SERVICE_ACCOUNT@$PROJECT_ID.iam.gserviceaccount.com"

      - name: Configure Docker
        run: gcloud auth configure-docker $REGION_NAME-docker.pkg.dev --quiet

      - name: Build Docker image
        run: docker build ./complete -t $REGION_NAME-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME

      - name: Push Docker image
        run: docker push $REGION_NAME-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME

      # Setup gcloud CLI google
      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
        export_default_credentials: true

     # - name: Configure GKE access 1
     #   run: gcloud components install gke-gcloud-auth-plugin
     # - name: Configure GKE access 2
     #   run: gcloud container clusters get-credentials $CLUSTER_NAME --region=$REGION_NAME

      #- id: deploy
      #  name: Deploy Docker image
      #  uses: "google-github-actions/deploy-cloudrun@v0"
      #  with:
      #    image: ${{ env.IMAGE_NAME }}
      #    region: us-central1
      #    service: app
      #    flags: --port=8080

      # Example of using the output
      #- name: Test URL
      #  run: curl "${{ steps.deploy.outputs.url }}"